# grafana/provisioning/datasources/mysql.yml
apiVersion: 1

datasources:
  - name: MySQL Traffic
    type: mysql
    access: proxy
    url: mysql-traffic:3306
    database: traffic_db
    user: grafana
    secureJsonData:
      password: "grafana"
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      tlsAuth: false
      tlsAuthWithCACert: false
